### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by nerddd** [janivanecky/Hair#1]
Sorry,I used your project,but there is no detail config guidence. So ther is something wrong when I build it.
The platform I use is Windows7 VS2015.And I saw your folder named "lib",There are just some .h or .cpp files.So I only add these 

_IncludePath:_ ..\lib\SDL2-2.0.3\include;..\lib\glew-1.10.0\include;..\lib\glm\glm;

But I got the follwing error messages

> 
> LNK2019	无法解析的外部符号 SDL_CreateWindow，该符号在函数 "bool __cdecl InitWindow(void)" (?InitWindow@@YA_NXZ) 中被引用	Hair	C:\Users\cl\Desktop\test\Hair-master\Hair\main.obj	
> 
> LNK2019	无法解析的外部符号 SDL_GetMouseState，该符号在函数 "void __cdecl ImGui_ImplSdlGL3_NewFrame(void)" (?ImGui_ImplSdlGL3_NewFrame@@YAXXZ) 中被引用	Hair	C:\Users\cl\Desktop\test\Hair-master\Hair\imgui_impl_sdl_gl3.obj
> 
> LNK2001	无法解析的外部符号 SDL_GetTicks	Hair	C:\Users\cl\Desktop\test\Hair-master\Hair\main.obj
> 
> LNK2019	无法解析的外部符号 __imp_glTexParameteri，该符号在函数 "void __cdecl ImGui_ImplSdlGL3_CreateFontsTexture(void)" (?ImGui_ImplSdlGL3_CreateFontsTexture@@YAXXZ) 中被引用	Hair	C:\Users\cl\Desktop\test\Hair-master\Hair\imgui_impl_sdl_gl3.obj	

etc
It seems that something wrong with SDL and OpenGL?
Any help or addvice will be appreciated!

**Comment by nerddd** [comment]
Solved.

**Comment by ReneWu1117** [comment]
I meet a similar problem, can you explain you way?

**Comment by panganqi** [comment]
how did you fix that ?
